- name: Install ssh (required by MPI)
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    name:
    - ssh

- name: Set Conda binary path
  set_fact:
    conda_code_bin: "{{ conda_code_parent_dir }}/{{ conda_code_link_dir }}/bin/conda"

- name: install Conda
  include_role:
    name: andrewrothstein.miniconda
  vars:
    miniconda_parent_dir: "{{ conda_code_parent_dir }}"
    miniconda_link_subdir: "{{ conda_code_link_dir }}"
    miniconda_ver: "{{ conda_code_miniconda_ver }}"
    miniconda_python_ver: "{{ conda_code_python_version | replace('.', '') }}"
    miniconda_escalate: false
    miniconda_pkg_update: false  # this is not idempotent

- name: Initialise Conda for bash shell
  command: "{{ conda_code_bin }} init -q bash"
  changed_when: false

# TODO these settings could be set by direct modification of ${HOME}/.condarc
- name: Set auto_activate_base to {{ conda_code_auto_activate }}
  command: "{{ conda_code_bin }} config --set auto_activate_base {{ 'true' if conda_code_auto_activate else 'false' }}"
  changed_when: false
- name: Make conda-forge default channel
  command: "{{ conda_code_bin }} config --prepend channels conda-forge"
  changed_when: false

- name: Create envs
  command: "{{ conda_code_bin }} create -qy -c conda-forge --override-channels -n {{ env.name }} {{ env.packages | join(' ') }}"
  args:
    creates: "{{ conda_code_parent_dir }}/{{ conda_code_link_dir }}/envs/{{ env.name }}"
  loop: "{{ conda_code_envs }}"
  loop_control:
    loop_var: env

- name: Clean Conda
  command: "{{ conda_code_bin }} clean -tipsyq"
  changed_when: false

# TODO test codes
